[build]
  # Comando para instalar las dependencias de Python
  command = "pip install -r requirements.txt"
  
  # Directorio donde Netlify buscará tus funciones serverless
  functions = "netlify/functions/"

# Redirección clave para que todas las peticiones lleguen a tu app de Flask
[[redirects]]
  # Captura cualquier ruta que no sea un archivo estático
  from = "/*"
  
  # Envía la petición a la función 'api.py'
  to = "/.netlify/functions/app"
  
  # Código 200 para que la URL no cambie en el navegador (es una reescritura, no una redirección)
  status = 200
  